### ISSUE TITLE
support repo - https://github.com/*/releases/tag/*

### ISSUE THREAD

**Issue by ctownshend** [sonatype-nexus-community/nexus-iq-chrome-extension#161]

**Comment by roger-lau** [comment]
When we use this on the Github release page, it always returns on result from OSS Index. 

The issue is: the URL generated by Chrome plugin is https://ossindex.sonatype.org/component/pkg:github/jquery/jquery@1.11.1
That has no vulnerability.

The OSS Index URL that shows vulnerability in jquery is https://ossindex.sonatype.org/component/pkg:npm/jquery@1.11.

Can we fix this?
